language: rust

rust:
  - 1.26.0              # minimum supported toolchain
  - nightly-2017-10-08  # pinned toolchain for clippy
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - CLIPPY_VERSION=0.0.165
    - CLIPPY_RUST_VERSION=nightly-2017-10-08

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      cargo install clippy --vers $CLIPPY_VERSION --force;
    fi'

script:
  - cargo test
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      cargo clippy -- -D warnings;
    fi'
